INSERT INTO MONEY VALUES (1, 200);
INSERT INTO MONEY VALUES (2, 1100);

INSERT INTO ACCOUNT VALUES (1, 'ACC_ORIGIN', TRUE, 1, 'EUR');
INSERT INTO ACCOUNT VALUES (2, 'ACC_DESTINATION', TRUE, 2, 'EUR');